$ docker ps -a
CONTAINER ID   IMAGE          COMMAND                  CREATED          STATUS                        PORTS     NAMES
aee112469568   hello-docker   "sh"                     17 minutes ago   Exited (0) 16 minutes ago               intelligent_hamilton
ae8b6a22db9c   hello-docker   "sh"                     18 minutes ago   Exited (130) 17 minutes ago             naughty_dirac
7505640c8111   hello-docker   "sh"                     6 hours ago      Exited (255) 3 hours ago                brave_driscoll
5d48e81bb879   hello-docker   "/bin/sh -c ./hello.…"   6 hours ago      Exited (0) 6 hours ago                  unruffled_hertz
859f5657af43   alpine/git     "git clone https://g…"   7 hours ago      Exited (0) 7 hours ago                  repo
8560716f99d3   c0ae79d28281   "ls"                     10 days ago      Exited (0) 10 days ago                  serene_pascal
1bde83f1a0d6   c0ae79d28281   "sh"                     10 days ago      Exited (0) 10 days ago                  musing_pike
f9924a55c734   c0ae79d28281   "sh"                     10 days ago      Exited (130) 10 days ago                jovial_kilby
bc370d0bf282   ubuntu         "/bin/bash"              10 days ago      Exited (0) 10 days ago                  hungry_swartz
6818510ef774   nginx          "/docker-entrypoint.…"   10 days ago      Exited (0) 10 days ago                  nostalgic_burnell